### ISSUE TITLE
It's impossible figure out how to sort by track number

### ISSUE THREAD

**Issue by mihaipora** [medoc92/upplay#13]
I read in the help page that right click on playlist entries and select 'sort by track number', but the only thing I see in the contextual menu is 'Remove'.

Can you update the help to be more specific on how to sort by track number ?
Ideally, I would like to do that when adding from the file list because if I add 2 albums and I want them to play one after another A1,A2,A3,A4 .. B1,B2,B3,B4 , not interleaved as I imagine it would happen if I sort by track number after adding 2 albums A1 , B1, A2, B2 .. 

Now the good parts: I'm using the app to play music from my nas to foobar2000 renderer from my Chromebook with crouton. 
Using Debian trusty, I just followed the installation instructions and there are no compatibility issues.

Thanks,
Mihai

**Comment by medoc92** [comment]
You don't mention what version you are using but I'm guessing it is a release. The sort by tno function is only in the github  code for now. I think that there are also sort options on the directory side, which you can use before add, but I can't be more precise at the moment because I only have a mobile phone around, I don't remember the details and I can't try

**Comment by mihaipora** [comment]
You are right, I used the release version.

**Comment by medoc92** [comment]
Fixed by https://github.com/medoc92/upplay/commit/beee5b1ba3912462fae378b9dc99bf0224a22793
