### ISSUE TITLE
Windows version without title bar

### ISSUE THREAD

**Issue by marc-aurel** [medoc92/upplay#15]
first thanks, a lovely program to control UPnP devices via Windows!

Unfortunately when I start the program (under Windows 10 32bit) there is no title bar. The menu is directly shown in the upper left corner of my screen. So I can't move, resize or minimize the window. Full screen works but then I have to use keyboard shortcuts to get back to my normal desktop.

**Comment by medoc92** [comment]
Thanks for reporting this. As mentionned on the download page, the Windows version is still very much an experiment, but I do want to make it work.

I need to install a Windows 10 machine for testing, and also probably to port Upplay to Qt 5.4 or later, because official Windows 10 support apparently came with Qt 5.4.1. 

This means that I will probably need to use the new Webengine HTML renderer, which will need some adaptations in Upplay.

All this will take some time, but, again, thanks very much for testing and reporting, I hope that I can make this application more useful in the future.

Cheers,

jf

**Comment by finvarg** [comment]
Hi, i have same problem on Win 7 64 bit.

**Comment by medoc92** [comment]
Hi, Windows development is stopped at the moment, because my free Visual Studio 2013 license expired , I guess that there is only free VS 2015 now, which Qt does not support yet. As soon as VS 2015 Qt arrives, I'll resume working on this.

**Comment by medoc92** [comment]
I think it's fixed by https://github.com/medoc92/upplay/commit/3a116ff5b7973afc3735014689d03a3fea52e316

This is in the new windows binaries (qt5.5 + MinGW) on the web site.
