### ISSUE TITLE
Control Philips Streamium NP1100 upnp renderer

### ISSUE THREAD

**Issue by arthurlutz** [medoc92/upplay#16]
When launching upplay (installed via ubuntu PPA) I can only see my kodi instance as a renderer, not my NP1100 upnp device (seen by upnp-inspector). Any chance of being able to control that device too ? Is is a https://github.com/medoc92/libupnpp bug ? I can supply the list of primitives supported by that device if needed.

**Comment by medoc92** [comment]
One thing to try would be to to start upplay as follows:

    UPPLAY_LOGLEVEL=6 upplay 2> /tmp/trace

Then please attach the trace. Possibly scan it for privacy issues, but there shouldn't be much beyond IP addresses. You can also send it by email: jf at dockes dot org.

If I can see nothing in there, yes, we can have a try with a list of primitives, or dumps from upnp-inspector.

It might be an upplay or libupnpp issue, it does not make much difference where the issue is attached :)

Cheers,
jf

**Comment by medoc92** [comment]
No feedback
