### ISSUE TITLE
Show more data in browse list

### ISSUE THREAD

**Issue by rfritzzz** [medoc92/upplay#18]
It would be nice to display a little more data in the browse list.

For example when browsing albums it would be nice to display the artist as well.

I understand that upplay just display what comes from the upnp server. I checked if it's possible with bubbleupnp and there you can see the artist in albums. I don't know if bubbleupnp has some special logic for that.

**Comment by Pastim** [comment]
I'd be against this unless optional (no least because my tracks can have many artists).

**Comment by medoc92** [comment]
Actually, I gave it a try, and it's quite useful, because albums of the same name by different artists are quite common. By limiting the length of the artist data (to 15 chars in the current code), it just uses wasted space on the right of the album titles and I think that it's quite useful.

I committed an experimental patch (it's just a few lines because the data *is* sent by minim with the album list, no special logic needed), please take a look if you have a moment.

This can still be reverted and/or be made optional (I could also add a parameter for the truncation length, upplay preferences need an overhaul anyway).

**Comment by Pastim** [comment]
Please make it optional!  This really won't work for me otherwise, just giving a random partial artist name when there can be 10 or more I might want to know about.

I might also ask which 'artist' you are using, since there are several flavours (Including Artist,  Album Artist, AlbumArtist, and so on).  Minimserver can include Composer and other tags as well, so this is not a simple matter.

**Comment by medoc92** [comment]
Ok, the last commits add a preferences panel to replace the preferences menu. I added preferences to display artist info or not and adjust the truncation when it is displayed.
