### ISSUE TITLE
Display thumbnails (album art) in lists

### ISSUE THREAD

**Issue by colorcube** [medoc92/upplay#19]
It would be very nice if (optionally) album art can be displayed in the lists.
A tile view with bigger images would be nice too.

I guess it slows down display so it might be needed to cache the images or load the files asynchronous.

**Comment by Pastim** [comment]
I wouldn't want this, so if supported I'd ask that it be optional.

**Comment by medoc92** [comment]
Apart from the performance issue (which can be solved), I'm not too keen on the idea in list view because this is going to waste a lot of vertical space. Bubble can do this on a tablet because crowded lines would make for a difficult touch interface anyway, but this limits the visible list to 5-10 titles (on my Nexus 7). upplay could display around 30 entries in an equivalent space.

A tile view would sometimes make sense (for example when displaying all the albums for a given artist). I'm not too sure how to do this in HTML so that it behaves properly with window resizes. Needs a bit of HTML experimentation first. Any ideas ?

**Comment by rfritzzz** [comment]
It seems people are interested to see those things optional and I agree.
But making it optional is the smaller amount of work right?

I had a look in the code and it is interesting that the list is made with a html view. Building a tile view that adapts to the window width is not that hard. I'm willing to experiment with it in the next days.

**Comment by rfritzzz** [comment]
I have a prototype running which shows album art. I like it ;-)
It seems the image files will be loaded every time again. I guess it's possible to enable caching for the web view?

**Comment by medoc92** [comment]
Not too sure about the caching, I'd have to look at the qt webkit doc. 

How do you load the images ?

The content directory browser is a bit of a mess currently, it's a proof of concept turned app. We'd need much better separation between the presentation, the data, and the c++ code. I'm not too sure how to do this though.
