### ISSUE TITLE
Source names not obvious 

### ISSUE THREAD

**Issue by artmg** [medoc92/upplay#29]
Hi JF, many thanks for yet another great foss linux tool!

Running upplay 1.2.2 on recent fresh Lubuntu 15.10 install, I browse for Sources and see Playlist (Playlist) rather than the device name or description. My source is Volumio MPD on Pi (ever heard of upmpd ;) and gupnp-universal-cp correctly shows the device with the first serviceId as "Playlist" - perhaps the source dialog needs to look at its parent?

Please let me know if you would like any diagnostic output posting or pastebinning
je te remerci

**Comment by medoc92** [comment]
Hi,

I wonder if you may be confusing "Select source" and "Select Media renderer" ?

Select Source is used to select one source among potentially several that the OpenHome renderer may have. 

It happens that the basic upmpdcli install only has one Playlist/Playlist (source type/name). 

if you opened the same tool on, for example, Pete Manchester MediaPlayer, you would also see a "Radio" source. Selecting this would change the playlist area to display a list of channels.

The latest upmpdcli/sc2mpd installs also have other selectable "Sources" dealing with Songcast.

Or maybe I'm wrong about what you mean...

**Comment by artmg** [comment]
I was indeed talking about the "_Select Source_" dialog. The "Select Media Renderer" dialog shows that device with the correct Hostname :)

So, are you saying its a limitation with the server on **Volumio**'s software stack? I am running **v1.55** of that distro which carries **upmpcli v0.8.1-1**. I will try updating that software to see if the newer versions help. I will also check once I have other media sources available on the network. I'll open another ticket with any ongoing issues.

Thanks!

**Comment by medoc92** [comment]
I think that we don't have the same definition of "Source". For upplay, a Source is an OpenHome notion, it's one type of input inside an OpenHome renderer (Playlist, Radio, Receiver...). Older upmpdcli releases had no Songcast Receiver source, that's why I mentionned a version issue, but now, I don't think that's what you mean any more, because "other source on the network" does not match this context. 

Do you mean a Content Directory (a machine serving audio files) ?

Content Directories are supposedly listed in the right-hand window.

Please define what you call "Media source". I don't think that this is related to Volumio issues.
