### ISSUE TITLE
GUI looks (unsurprisingly) awful on HiDPI screen

### ISSUE THREAD

**Issue by hv15** [medoc92/upplay#30]
Discovered your app, which works fantastically with MiniDLNA and a Sony SA-NS510, but sadly looks (unsurprisingly) awful on a HiPDI display (3840x2160px).

Here is a screenshot of what it looks like: ![upplay](https://cloud.githubusercontent.com/assets/2742854/12488752/0d5dbba4-c065-11e5-9f0e-b0420e1681c7.jpg)

As you can see, everything is very small and very difficult to read. I run my xserver running at a DPI/PPI of 282 which has been working well for most apps. For GDK and Qt apps I have the following environmental variables set:

```
GDK_DPI_SCALE=0.5
GDK_SCALE=2
QT_DEVICE_PIXEL_RATIO=2
```

It would be great if this could be fixed, perhaps by adding something to scale the fonts/ui elements up?

**EDIT**: Just had a look to see what effect `QT_DEVICE_PIXEL_RATIO` has, but it seems to do nothing to the UI scaling.

**Comment by medoc92** [comment]
I think that you should be able to adjust the directory browser font size by editing /usr/share/upplay/dirbrowser/cdbrowser.css, for example, add something like the following at the beginning:

````
html, body, form, fieldset, table, tr, td, img {
    font-family:Arial,helvetica,sans-serif;
    font-size:150%;
}
````

Unfortunately, I have no idea whatsoever why the left part looks so awful, this is code inherited from Sayonara, which I don't know well. I'd like to take a look at how this kind of thing is usually be done, and fix upplay for hi res displays, but I won't be able to do much in the next ten days or such.

**Comment by DavidBIW** [comment]
Where does this issue currently stand? I have just installed Upplay on a Surface 3 tablet, and it is unfortunately unusable on the touch screen. The font size adjustment you suggested in the previous post does not appear to work in Windows.

**Comment by medoc92** [comment]
I did not have time to look at this, it's still in the plans. It's made a bit difficult by the fact that I have no such device to test on. 

By the way, upplay is really a boring old desktop app. I am curious about why you would want to use it on a tablet rather that a more modern and touch-oriented application (maybe Kazoo ?)

**Comment by DavidBIW** [comment]
Firstly, apologies. The fix does work, to a degree, or at least it does on my Surface 3, once I followed your instructions correctly. However, I have had to experiment to find the most usable font value. On the Surface 3, 115% seems to provide the best value for browsing the MinimServer indexes. Unfortunately, this makes the server selection font too small, and seems to have no effect on the playlist font, which ideally needs to be a bit larger. Still, I can now use the app, which is the object of the exercise.

Why use Upply rather than, say, Kinsky or Kazoo, both of which are installed on my Surface? Kazoo works well, while Kinsky seems to have issues whenever I switch between wireless and Ethernet networking (I have a dock for the Surface which allows the use of Ethernet). But both make inefficient use of screen real estate. In reality, 90%+ of the information you really need on a control point is text-based. True, album cover art provides good visual clues. But if you have a lot of long classical titles as I do, being able to fit as much (readable and touch-selectable) text as possible into the allocated window space is a big advantage. So I think that, Upplay, plain and 'boring' as it is, quite often does a better job than the fancier apps, and I like to have it as one of the available applications.

**Comment by medoc92** [comment]
Thank you for the explanation.

I have uploaded a slightly experimental release to the site: http://www.lesbonscomptes.com/upplay/downloads/windows/upplaysetup-1.2.5pre1-w1.exe

This allows adjusting almost all font sizes by editing 2 css files. Things are not quite perfect, because the size of the player section, and the different icons are not adjusted, but this is a first step.

There is a description of the release changes on the windows page: http://www.lesbonscomptes.com/upplay/upplay-windows.html

The modifications to be performed are described in slightly more detail at the bottom of the "manual": http://www.lesbonscomptes.com/upplay/upplay.html#hiresadjust

**Comment by DavidBIW** [comment]
Apologies for not responding sooner, because of family commitments over the holiday. I am now able to try the experimental release, and will do so over the next couple of days.

In principle, I like the idea of editing the CSS file, so I am looking forward to making this work. Thank you for your effort.

David

**Comment by DavidBIW** [comment]
I have now done some testing, and the changes I was able to make were significant improvements. I have written in directly with a few small comments, but the only point I need to record here is that the changes do need to be applies with a light touch. I'd begin by simply uncommenting the 30px text size in cdbrowser.css, and working incrementally from there.

David

**Comment by medoc92** [comment]
Hi,

No need for apologies, nothing urges here. Family first :)

 "I have written in directly..." Do you mean that you sent an email ? Because I did not receive anything.

Jf

**Comment by DavidBIW** [comment]
I sent the email to the proper address. It reported generally good success with version 1.25pre1. Just one housekeeping point. On my Windows 10 machine, I had to run the installer "as administrator". Likewise, I had to run my text editor as administrator in order to be able to save the edited .css files.

The attached screenshot from my main PC (1920 x 1200 resolution) provides an interesting contrast to the screenshot attached to the opening post.
![upplay_1 25pre1](https://cloud.githubusercontent.com/assets/18103515/14206180/4bbd624c-f809-11e5-9977-2555d81c025f.jpg)

**Comment by PrzemoF** [comment]
Maybe it's worth to try this if the upplay can go with qt5:
"Migration of Existing Applications

In order to get an application designed for low DPI values running on a high resolution monitors quickly, consider one of the scaling options (let the application run as DPI Unaware on Windows or set the environment variable QT_AUTO_SCREEN_SCALE_FACTOR to "1". These options may incur some scaling or painting artifacts, though."

http://doc.qt.io/qt-5/highdpi.html

**Comment by medoc92** [comment]
@PrzemoF thanks for the idea. Actually upplay is already using QT5 on most platforms (when building and if several development packages are installed you just need to take care to use the right version of qmake).

The issue is made a little complicated by the fact that the right part of the app is actually a web browser, and the contents are HTML. This makes certain things easier, but consistency with the rest of the app (fonts/colors etc.) is not automatic.

**Comment by medoc92** [comment]
Not sure I can do anything more at this point esp. given that I have no display appropriate for testing
