### ISSUE TITLE
Switching between SourceType Radio and Playlist

### ISSUE THREAD

**Issue by Floo** [medoc92/upplay#31]
Hi,

I can switch between Radio and Playlist using the upplay-GUI. Everything works fine. However, if I listen to internet radio and start playing a track from a playlist using another controlpoint than upplay, e.g. BubbleUPNP, upplay does not automatically switch back from SourceType Radio to Playlist. Both, BubbleUPNP and Upplay show unexpected behaviour. I dont know if this is an issue of upplay or upmpdcli.

**Comment by medoc92** [comment]
Hi,

Thanks for reporting this.

I took a look, and the issue is actually a bit complicated, and things work or don't work according to a number of factors.

I've changed the code in upmpdcli to be more consistent in generating an error in this situation, or handle the cases where things can work.

Hopefully, the latest git upmpdcli should switch from Radio to Playlist when adding a track from BubbleUPnP.

The right approach would  be, even if a bit inconvenient, to first switch the source from Bubble (this would mean using BubbleDS as the regular version does not seem to know about sources).

Unfortunately, switching sources from BubbleDS does not work well either, the source changes all right (and upplay currently picks up the event), but, in some cases, you need to restart (or just connect again to the renderer) for the change to be fully acknowledged.

As far as I can see, upplay properly picks up the state changes.

**Comment by medoc92** [comment]
With the latest git versions of libupnpp and upmpdcli, bubbleDS picks up the external switches between Playlist and Radio, lists the radio stations even when the Source is Playlist. In addition switching using the source menu works, and switching by directly clicking a radio or a playlist track "sometimes" work. There is not much more I can do due to the internal upmpdcli implementation.
