### ISSUE TITLE
Please Display full Artist(and Album) information.

### ISSUE THREAD

**Issue by tack1953** [medoc92/upplay#53]
Hello,
Thank you for this convinient application.
I found bug(or the behavior by design?) concerning displaying artist and album name.
When the title of the tune is very long(like classical one), the name of album is truncated.
Here is the screenshot, 

http://imgur.com/a/ki1Po

in this case track7 ,album name [ Chopin Complete Edition ] is truncated and displayed
such as [ Chopin Complet
To avoid this issue, use mouse and move the boundary (between playlists view and Contents view) rightward
and broaden the width of plalist view.
Maybe it's not a problem, but I wuold like upplay to display the entire artists and album name even if the width of playlists view is 
not wide enough to display the full title of the tune.

I posted this article in upplay web page comment field by mistake.
Please delete them.

**Comment by tack1853** [comment]
Additionaly, I confirmed Garbled characters bug in upplay1.2.7(debian linux).
Characters of contents displayed correctly, but directory name including Japanese UTF-8 would be Garbled characters.  I swtched back to upplay 1.2.6, in 1.2.6 displayed correctly.

**Comment by tack1953** [comment]
Sorry , I forgot to my environment. I use MinimServer 0.8.4 update 88 as uPnP server.

**Comment by medoc92** [comment]
I need to look at the code to see why this excessive truncation occurs. But there is a basic issue with the track duration: if I display untruncated album and artist info, the track length will go off-screen. 

There are different possibilities:

1. Let it become inaccessible
2. Improve the truncation issue but keep the track length on the right (so that there will still be truncation in some cases).
3. Display the track duration on the left side.

What do you think ? 

The character display issue is fixed in git code.

**Comment by tack1853** [comment]
I think No.2 is desirable and natural.
Track length is also necessary information and most fo the applications display it on the right.
I'd like you to fix excessive truncation but even if so, there still are truncations of Alubm name 
 but it is inevitable.

**Comment by medoc92** [comment]
Ok, I'll gie a try to approach 2 next time I work on the program (busy with other stuff at the moment).

**Comment by tack1953** [comment]
Thank you for your reply.
I appreciate your efforts.

**Comment by medoc92** [comment]
This should be fixed by this commit: https://github.com/medoc92/upplay/commit/b5fa5ad5f3aac54983f1964ad710ba7546b07645
