### ISSUE TITLE
Workflow Improvements: Take Album+Artist into Account when sorting

### ISSUE THREAD

**Issue by cars10** [medoc92/upplay#56]
Would it be possible to take the album+artist into account when sorting? Sorting after title does not make sense if my playlist contains more then 1 album

Edit: i just realized that this is already done, not sure why i did not work for me. Maybe it would help to display the tracknumber in the playlist ?

**Comment by medoc92** [comment]
Yes, currently it sorts by album then track number.  

I am not sure that it would be such a good idea to display the track number, because if the playlist is a selection coming from multiple albums (e.g. all the versions of 'Summertime'), the track number does not make much sense (and we're already short on space in the playlist area).

I think that 'sort by tno' was implemented for the case where you added a directory corresponding to an album, and for some reason, the directory was not added in track number order (this happens with some media servers). Then you can easily fix the playlist.

**Comment by cars10** [comment]
Hm, now that i am thinking about it.. I guess that makes sense. Thanks!
