### ISSUE TITLE
Improvement: song list

### ISSUE THREAD

**Issue by PrzemoF** [medoc92/upplay#61]
Could you add sorting to the song list (click-to-sort, I know there is an option in Preferences)? And option to change column width...

P.S. Thanks a for a really nice piece of software! 🥇

**Comment by medoc92** [comment]
Do you mean something like clicking on a column header to change the sort order ? 

About the column widths: the directory area is HTML and I don't know how to make the columns resizeable. I guess that this would be feasible with a bit of javascript, but this looks complicated.

While I was looking at this anyway, I added classes to the columns so that it would be possible in theory to use css to adjust how the table works. In my tests, this is not very convincing, I generally prefer what the automatic sizing comes up with.


I added an entry to the popup which goes directly to the sorting preferences.

**Comment by PrzemoF** [comment]
Yes, click to sort would be great. The right click menu with sort order is very handy - I just tested it and works fine. Thanks!
